# The proper term is pseudo_replica_mode, but we use this compatibility alias
# to make the statement usable on server versions 8.0.24 and older.
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#251111  1:10:48 server id 1  end_log_pos 127 CRC32 0x59f8ae22 	Start: binlog v 4, server v 9.3.0 created 251111  1:10:48 at startup
# Warning: this binlog is either in use or was not closed properly.
ROLLBACK/*!*/;
# at 127
#251111  1:10:48 server id 1  end_log_pos 158 CRC32 0x1cc15e20 	Previous-GTIDs
# [empty]
# at 158
#251111  1:40:46 server id 1  end_log_pos 235 CRC32 0x52854b4b 	Anonymous_GTID	last_committed=0	sequence_number=1	rbr_only=no	original_committed_timestamp=1762792846702215	immediate_commit_timestamp=1762792846702215	transaction_length=248
# original_commit_timestamp=1762792846702215 (2025-11-11 01:40:46.702215 JST)
# immediate_commit_timestamp=1762792846702215 (2025-11-11 01:40:46.702215 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846702215*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 235
#251111  1:40:46 server id 1  end_log_pos 406 CRC32 0xc092f87f 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 96
use `pensieve`/*!*/;
SET TIMESTAMP=1762792846/*!*/;
SET @@session.pseudo_thread_id=12/*!*/;
SET @@session.foreign_key_checks=1, @@session.sql_auto_is_null=0, @@session.unique_checks=1, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=1168113696/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=255,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=DEFAULT/*!*/;
/*!80011 SET @@session.default_collation_for_utf8mb4=255*//*!*/;
DROP TABLE `anon1` /* generated by server */
/*!*/;
# at 406
#251111  1:40:46 server id 1  end_log_pos 483 CRC32 0x5ffac63b 	Anonymous_GTID	last_committed=1	sequence_number=2	rbr_only=no	original_committed_timestamp=1762792846709774	immediate_commit_timestamp=1762792846709774	transaction_length=230
# original_commit_timestamp=1762792846709774 (2025-11-11 01:40:46.709774 JST)
# immediate_commit_timestamp=1762792846709774 (2025-11-11 01:40:46.709774 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846709774*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 483
#251111  1:40:46 server id 1  end_log_pos 636 CRC32 0x7bf173cf 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 97
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon2` /* generated by server */
/*!*/;
# at 636
#251111  1:40:46 server id 1  end_log_pos 713 CRC32 0xd9de9eb6 	Anonymous_GTID	last_committed=2	sequence_number=3	rbr_only=no	original_committed_timestamp=1762792846731786	immediate_commit_timestamp=1762792846731786	transaction_length=226
# original_commit_timestamp=1762792846731786 (2025-11-11 01:40:46.731786 JST)
# immediate_commit_timestamp=1762792846731786 (2025-11-11 01:40:46.731786 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846731786*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 713
#251111  1:40:46 server id 1  end_log_pos 862 CRC32 0xeb3741d3 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 98
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon3` /* generated by server */
/*!*/;
# at 862
#251111  1:40:46 server id 1  end_log_pos 939 CRC32 0x1549a637 	Anonymous_GTID	last_committed=3	sequence_number=4	rbr_only=no	original_committed_timestamp=1762792846760194	immediate_commit_timestamp=1762792846760194	transaction_length=218
# original_commit_timestamp=1762792846760194 (2025-11-11 01:40:46.760194 JST)
# immediate_commit_timestamp=1762792846760194 (2025-11-11 01:40:46.760194 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846760194*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 939
#251111  1:40:46 server id 1  end_log_pos 1080 CRC32 0x52f13225 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 99
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon4` /* generated by server */
/*!*/;
# at 1080
#251111  1:40:46 server id 1  end_log_pos 1157 CRC32 0x195c25b5 	Anonymous_GTID	last_committed=4	sequence_number=5	rbr_only=no	original_committed_timestamp=1762792846769075	immediate_commit_timestamp=1762792846769075	transaction_length=235
# original_commit_timestamp=1762792846769075 (2025-11-11 01:40:46.769075 JST)
# immediate_commit_timestamp=1762792846769075 (2025-11-11 01:40:46.769075 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846769075*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 1157
#251111  1:40:46 server id 1  end_log_pos 1315 CRC32 0xfee722db 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 100
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon5` /* generated by server */
/*!*/;
# at 1315
#251111  1:40:46 server id 1  end_log_pos 1392 CRC32 0x45b9e45a 	Anonymous_GTID	last_committed=5	sequence_number=6	rbr_only=no	original_committed_timestamp=1762792846776178	immediate_commit_timestamp=1762792846776178	transaction_length=231
# original_commit_timestamp=1762792846776178 (2025-11-11 01:40:46.776178 JST)
# immediate_commit_timestamp=1762792846776178 (2025-11-11 01:40:46.776178 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846776178*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 1392
#251111  1:40:46 server id 1  end_log_pos 1546 CRC32 0x06064c2e 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 101
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon6` /* generated by server */
/*!*/;
# at 1546
#251111  1:40:46 server id 1  end_log_pos 1623 CRC32 0x74cbe12b 	Anonymous_GTID	last_committed=6	sequence_number=7	rbr_only=no	original_committed_timestamp=1762792846792606	immediate_commit_timestamp=1762792846792606	transaction_length=235
# original_commit_timestamp=1762792846792606 (2025-11-11 01:40:46.792606 JST)
# immediate_commit_timestamp=1762792846792606 (2025-11-11 01:40:46.792606 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846792606*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 1623
#251111  1:40:46 server id 1  end_log_pos 1781 CRC32 0xc1d09d7d 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 102
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon7` /* generated by server */
/*!*/;
# at 1781
#251111  1:40:46 server id 1  end_log_pos 1858 CRC32 0x3767d57c 	Anonymous_GTID	last_committed=7	sequence_number=8	rbr_only=no	original_committed_timestamp=1762792846818067	immediate_commit_timestamp=1762792846818067	transaction_length=229
# original_commit_timestamp=1762792846818067 (2025-11-11 01:40:46.818067 JST)
# immediate_commit_timestamp=1762792846818067 (2025-11-11 01:40:46.818067 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846818067*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 1858
#251111  1:40:46 server id 1  end_log_pos 2010 CRC32 0x2644edb5 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 103
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon8` /* generated by server */
/*!*/;
# at 2010
#251111  1:40:46 server id 1  end_log_pos 2087 CRC32 0xd1a3ad18 	Anonymous_GTID	last_committed=8	sequence_number=9	rbr_only=no	original_committed_timestamp=1762792846824727	immediate_commit_timestamp=1762792846824727	transaction_length=224
# original_commit_timestamp=1762792846824727 (2025-11-11 01:40:46.824727 JST)
# immediate_commit_timestamp=1762792846824727 (2025-11-11 01:40:46.824727 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846824727*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 2087
#251111  1:40:46 server id 1  end_log_pos 2234 CRC32 0x379289b5 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 104
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon9` /* generated by server */
/*!*/;
# at 2234
#251111  1:40:46 server id 1  end_log_pos 2311 CRC32 0xb7ce4456 	Anonymous_GTID	last_committed=9	sequence_number=10	rbr_only=no	original_committed_timestamp=1762792846831648	immediate_commit_timestamp=1762792846831648	transaction_length=224
# original_commit_timestamp=1762792846831648 (2025-11-11 01:40:46.831648 JST)
# immediate_commit_timestamp=1762792846831648 (2025-11-11 01:40:46.831648 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846831648*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 2311
#251111  1:40:46 server id 1  end_log_pos 2458 CRC32 0x7c6ed0e7 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 105
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon10` /* generated by server */
/*!*/;
# at 2458
#251111  1:40:46 server id 1  end_log_pos 2535 CRC32 0x22df5e93 	Anonymous_GTID	last_committed=10	sequence_number=11	rbr_only=no	original_committed_timestamp=1762792846840356	immediate_commit_timestamp=1762792846840356	transaction_length=226
# original_commit_timestamp=1762792846840356 (2025-11-11 01:40:46.840356 JST)
# immediate_commit_timestamp=1762792846840356 (2025-11-11 01:40:46.840356 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846840356*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 2535
#251111  1:40:46 server id 1  end_log_pos 2684 CRC32 0x446d211e 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 106
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon11` /* generated by server */
/*!*/;
# at 2684
#251111  1:40:46 server id 1  end_log_pos 2761 CRC32 0xf4698ada 	Anonymous_GTID	last_committed=11	sequence_number=12	rbr_only=no	original_committed_timestamp=1762792846845500	immediate_commit_timestamp=1762792846845500	transaction_length=240
# original_commit_timestamp=1762792846845500 (2025-11-11 01:40:46.845500 JST)
# immediate_commit_timestamp=1762792846845500 (2025-11-11 01:40:46.845500 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846845500*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 2761
#251111  1:40:46 server id 1  end_log_pos 2924 CRC32 0xbb1786cf 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 107
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon12` /* generated by server */
/*!*/;
# at 2924
#251111  1:40:46 server id 1  end_log_pos 3001 CRC32 0x82bfaa33 	Anonymous_GTID	last_committed=12	sequence_number=13	rbr_only=no	original_committed_timestamp=1762792846857455	immediate_commit_timestamp=1762792846857455	transaction_length=234
# original_commit_timestamp=1762792846857455 (2025-11-11 01:40:46.857455 JST)
# immediate_commit_timestamp=1762792846857455 (2025-11-11 01:40:46.857455 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846857455*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 3001
#251111  1:40:46 server id 1  end_log_pos 3158 CRC32 0xd59da062 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 108
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon13` /* generated by server */
/*!*/;
# at 3158
#251111  1:40:46 server id 1  end_log_pos 3235 CRC32 0x827fa640 	Anonymous_GTID	last_committed=13	sequence_number=14	rbr_only=no	original_committed_timestamp=1762792846865874	immediate_commit_timestamp=1762792846865874	transaction_length=221
# original_commit_timestamp=1762792846865874 (2025-11-11 01:40:46.865874 JST)
# immediate_commit_timestamp=1762792846865874 (2025-11-11 01:40:46.865874 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846865874*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 3235
#251111  1:40:46 server id 1  end_log_pos 3379 CRC32 0x33c372b7 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 109
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon14` /* generated by server */
/*!*/;
# at 3379
#251111  1:40:46 server id 1  end_log_pos 3456 CRC32 0x0e33e542 	Anonymous_GTID	last_committed=14	sequence_number=15	rbr_only=no	original_committed_timestamp=1762792846872109	immediate_commit_timestamp=1762792846872109	transaction_length=239
# original_commit_timestamp=1762792846872109 (2025-11-11 01:40:46.872109 JST)
# immediate_commit_timestamp=1762792846872109 (2025-11-11 01:40:46.872109 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846872109*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 3456
#251111  1:40:46 server id 1  end_log_pos 3618 CRC32 0x9f526a9d 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 110
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon15` /* generated by server */
/*!*/;
# at 3618
#251111  1:40:46 server id 1  end_log_pos 3695 CRC32 0x24fd1c28 	Anonymous_GTID	last_committed=15	sequence_number=16	rbr_only=no	original_committed_timestamp=1762792846876167	immediate_commit_timestamp=1762792846876167	transaction_length=245
# original_commit_timestamp=1762792846876167 (2025-11-11 01:40:46.876167 JST)
# immediate_commit_timestamp=1762792846876167 (2025-11-11 01:40:46.876167 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846876167*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 3695
#251111  1:40:46 server id 1  end_log_pos 3863 CRC32 0xc04dac6c 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 111
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon16` /* generated by server */
/*!*/;
# at 3863
#251111  1:40:46 server id 1  end_log_pos 3940 CRC32 0xe52d7223 	Anonymous_GTID	last_committed=16	sequence_number=17	rbr_only=no	original_committed_timestamp=1762792846879338	immediate_commit_timestamp=1762792846879338	transaction_length=225
# original_commit_timestamp=1762792846879338 (2025-11-11 01:40:46.879338 JST)
# immediate_commit_timestamp=1762792846879338 (2025-11-11 01:40:46.879338 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846879338*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 3940
#251111  1:40:46 server id 1  end_log_pos 4088 CRC32 0x8746f6f2 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 112
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon17` /* generated by server */
/*!*/;
# at 4088
#251111  1:40:46 server id 1  end_log_pos 4165 CRC32 0xd4344141 	Anonymous_GTID	last_committed=17	sequence_number=18	rbr_only=no	original_committed_timestamp=1762792846892291	immediate_commit_timestamp=1762792846892291	transaction_length=248
# original_commit_timestamp=1762792846892291 (2025-11-11 01:40:46.892291 JST)
# immediate_commit_timestamp=1762792846892291 (2025-11-11 01:40:46.892291 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846892291*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 4165
#251111  1:40:46 server id 1  end_log_pos 4336 CRC32 0x4508e9dc 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 113
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon18` /* generated by server */
/*!*/;
# at 4336
#251111  1:40:46 server id 1  end_log_pos 4413 CRC32 0x8f84621a 	Anonymous_GTID	last_committed=18	sequence_number=19	rbr_only=no	original_committed_timestamp=1762792846901123	immediate_commit_timestamp=1762792846901123	transaction_length=242
# original_commit_timestamp=1762792846901123 (2025-11-11 01:40:46.901123 JST)
# immediate_commit_timestamp=1762792846901123 (2025-11-11 01:40:46.901123 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846901123*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 4413
#251111  1:40:46 server id 1  end_log_pos 4578 CRC32 0x3963da02 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 114
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon19` /* generated by server */
/*!*/;
# at 4578
#251111  1:40:46 server id 1  end_log_pos 4655 CRC32 0x6c88c2e5 	Anonymous_GTID	last_committed=19	sequence_number=20	rbr_only=no	original_committed_timestamp=1762792846914894	immediate_commit_timestamp=1762792846914894	transaction_length=233
# original_commit_timestamp=1762792846914894 (2025-11-11 01:40:46.914894 JST)
# immediate_commit_timestamp=1762792846914894 (2025-11-11 01:40:46.914894 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846914894*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 4655
#251111  1:40:46 server id 1  end_log_pos 4811 CRC32 0x54527703 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 115
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon20` /* generated by server */
/*!*/;
# at 4811
#251111  1:40:46 server id 1  end_log_pos 4888 CRC32 0x373aa31a 	Anonymous_GTID	last_committed=20	sequence_number=21	rbr_only=no	original_committed_timestamp=1762792846921898	immediate_commit_timestamp=1762792846921898	transaction_length=244
# original_commit_timestamp=1762792846921898 (2025-11-11 01:40:46.921898 JST)
# immediate_commit_timestamp=1762792846921898 (2025-11-11 01:40:46.921898 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846921898*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 4888
#251111  1:40:46 server id 1  end_log_pos 5055 CRC32 0xe792e39b 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 116
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon21` /* generated by server */
/*!*/;
# at 5055
#251111  1:40:46 server id 1  end_log_pos 5132 CRC32 0xc3b71810 	Anonymous_GTID	last_committed=21	sequence_number=22	rbr_only=no	original_committed_timestamp=1762792846927675	immediate_commit_timestamp=1762792846927675	transaction_length=226
# original_commit_timestamp=1762792846927675 (2025-11-11 01:40:46.927675 JST)
# immediate_commit_timestamp=1762792846927675 (2025-11-11 01:40:46.927675 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846927675*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 5132
#251111  1:40:46 server id 1  end_log_pos 5281 CRC32 0xd5cbb143 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 117
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon22` /* generated by server */
/*!*/;
# at 5281
#251111  1:40:46 server id 1  end_log_pos 5358 CRC32 0x36a0b4f3 	Anonymous_GTID	last_committed=22	sequence_number=23	rbr_only=no	original_committed_timestamp=1762792846939056	immediate_commit_timestamp=1762792846939056	transaction_length=226
# original_commit_timestamp=1762792846939056 (2025-11-11 01:40:46.939056 JST)
# immediate_commit_timestamp=1762792846939056 (2025-11-11 01:40:46.939056 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846939056*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 5358
#251111  1:40:46 server id 1  end_log_pos 5507 CRC32 0x42e3963a 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 118
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon23` /* generated by server */
/*!*/;
# at 5507
#251111  1:40:46 server id 1  end_log_pos 5584 CRC32 0xc4e05777 	Anonymous_GTID	last_committed=23	sequence_number=24	rbr_only=no	original_committed_timestamp=1762792846958452	immediate_commit_timestamp=1762792846958452	transaction_length=226
# original_commit_timestamp=1762792846958452 (2025-11-11 01:40:46.958452 JST)
# immediate_commit_timestamp=1762792846958452 (2025-11-11 01:40:46.958452 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846958452*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 5584
#251111  1:40:46 server id 1  end_log_pos 5733 CRC32 0xf88d47e5 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 119
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon24` /* generated by server */
/*!*/;
# at 5733
#251111  1:40:46 server id 1  end_log_pos 5810 CRC32 0x9ebef7f8 	Anonymous_GTID	last_committed=24	sequence_number=25	rbr_only=no	original_committed_timestamp=1762792846973330	immediate_commit_timestamp=1762792846973330	transaction_length=226
# original_commit_timestamp=1762792846973330 (2025-11-11 01:40:46.973330 JST)
# immediate_commit_timestamp=1762792846973330 (2025-11-11 01:40:46.973330 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846973330*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 5810
#251111  1:40:46 server id 1  end_log_pos 5959 CRC32 0x7d433f82 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 120
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon25` /* generated by server */
/*!*/;
# at 5959
#251111  1:40:46 server id 1  end_log_pos 6036 CRC32 0x60b3b815 	Anonymous_GTID	last_committed=25	sequence_number=26	rbr_only=no	original_committed_timestamp=1762792846977658	immediate_commit_timestamp=1762792846977658	transaction_length=221
# original_commit_timestamp=1762792846977658 (2025-11-11 01:40:46.977658 JST)
# immediate_commit_timestamp=1762792846977658 (2025-11-11 01:40:46.977658 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846977658*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 6036
#251111  1:40:46 server id 1  end_log_pos 6180 CRC32 0x705bf3d5 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 121
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon26` /* generated by server */
/*!*/;
# at 6180
#251111  1:40:46 server id 1  end_log_pos 6257 CRC32 0x429f5aae 	Anonymous_GTID	last_committed=26	sequence_number=27	rbr_only=no	original_committed_timestamp=1762792846982191	immediate_commit_timestamp=1762792846982191	transaction_length=215
# original_commit_timestamp=1762792846982191 (2025-11-11 01:40:46.982191 JST)
# immediate_commit_timestamp=1762792846982191 (2025-11-11 01:40:46.982191 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846982191*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 6257
#251111  1:40:46 server id 1  end_log_pos 6395 CRC32 0xeb98c38b 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 122
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon27` /* generated by server */
/*!*/;
# at 6395
#251111  1:40:46 server id 1  end_log_pos 6472 CRC32 0x0372d64b 	Anonymous_GTID	last_committed=27	sequence_number=28	rbr_only=no	original_committed_timestamp=1762792846986406	immediate_commit_timestamp=1762792846986406	transaction_length=227
# original_commit_timestamp=1762792846986406 (2025-11-11 01:40:46.986406 JST)
# immediate_commit_timestamp=1762792846986406 (2025-11-11 01:40:46.986406 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846986406*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 6472
#251111  1:40:46 server id 1  end_log_pos 6622 CRC32 0x5440ac8f 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 123
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon28` /* generated by server */
/*!*/;
# at 6622
#251111  1:40:46 server id 1  end_log_pos 6699 CRC32 0xb8f8cbf4 	Anonymous_GTID	last_committed=28	sequence_number=29	rbr_only=no	original_committed_timestamp=1762792846990133	immediate_commit_timestamp=1762792846990133	transaction_length=220
# original_commit_timestamp=1762792846990133 (2025-11-11 01:40:46.990133 JST)
# immediate_commit_timestamp=1762792846990133 (2025-11-11 01:40:46.990133 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846990133*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 6699
#251111  1:40:46 server id 1  end_log_pos 6842 CRC32 0x1458f90c 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 124
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon29` /* generated by server */
/*!*/;
# at 6842
#251111  1:40:46 server id 1  end_log_pos 6919 CRC32 0x0901f2c9 	Anonymous_GTID	last_committed=29	sequence_number=30	rbr_only=no	original_committed_timestamp=1762792846997468	immediate_commit_timestamp=1762792846997468	transaction_length=224
# original_commit_timestamp=1762792846997468 (2025-11-11 01:40:46.997468 JST)
# immediate_commit_timestamp=1762792846997468 (2025-11-11 01:40:46.997468 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792846997468*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 6919
#251111  1:40:46 server id 1  end_log_pos 7066 CRC32 0x6561f8cc 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 125
SET TIMESTAMP=1762792846/*!*/;
DROP TABLE `anon30` /* generated by server */
/*!*/;
# at 7066
#251111  1:40:47 server id 1  end_log_pos 7143 CRC32 0x68e5ac33 	Anonymous_GTID	last_committed=30	sequence_number=31	rbr_only=no	original_committed_timestamp=1762792847009120	immediate_commit_timestamp=1762792847009120	transaction_length=223
# original_commit_timestamp=1762792847009120 (2025-11-11 01:40:47.009120 JST)
# immediate_commit_timestamp=1762792847009120 (2025-11-11 01:40:47.009120 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792847009120*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 7143
#251111  1:40:47 server id 1  end_log_pos 7289 CRC32 0xa430db57 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 126
SET TIMESTAMP=1762792847/*!*/;
DROP TABLE `anon31` /* generated by server */
/*!*/;
# at 7289
#251111  1:40:47 server id 1  end_log_pos 7366 CRC32 0x7950fd7e 	Anonymous_GTID	last_committed=31	sequence_number=32	rbr_only=no	original_committed_timestamp=1762792847019356	immediate_commit_timestamp=1762792847019356	transaction_length=224
# original_commit_timestamp=1762792847019356 (2025-11-11 01:40:47.019356 JST)
# immediate_commit_timestamp=1762792847019356 (2025-11-11 01:40:47.019356 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792847019356*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 7366
#251111  1:40:47 server id 1  end_log_pos 7513 CRC32 0x47305dcc 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 127
SET TIMESTAMP=1762792847/*!*/;
DROP TABLE `anon32` /* generated by server */
/*!*/;
# at 7513
#251111  1:40:47 server id 1  end_log_pos 7590 CRC32 0xe6bab720 	Anonymous_GTID	last_committed=32	sequence_number=33	rbr_only=no	original_committed_timestamp=1762792847046801	immediate_commit_timestamp=1762792847046801	transaction_length=217
# original_commit_timestamp=1762792847046801 (2025-11-11 01:40:47.046801 JST)
# immediate_commit_timestamp=1762792847046801 (2025-11-11 01:40:47.046801 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792847046801*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 7590
#251111  1:40:47 server id 1  end_log_pos 7730 CRC32 0xdc3b0914 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 128
SET TIMESTAMP=1762792847/*!*/;
DROP TABLE `anon33` /* generated by server */
/*!*/;
# at 7730
#251111  1:40:47 server id 1  end_log_pos 7807 CRC32 0x4894cf9f 	Anonymous_GTID	last_committed=33	sequence_number=34	rbr_only=no	original_committed_timestamp=1762792847050650	immediate_commit_timestamp=1762792847050650	transaction_length=215
# original_commit_timestamp=1762792847050650 (2025-11-11 01:40:47.050650 JST)
# immediate_commit_timestamp=1762792847050650 (2025-11-11 01:40:47.050650 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792847050650*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 7807
#251111  1:40:47 server id 1  end_log_pos 7945 CRC32 0x5f7a3de6 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 129
SET TIMESTAMP=1762792847/*!*/;
DROP TABLE `anon34` /* generated by server */
/*!*/;
# at 7945
#251111  1:41:59 server id 1  end_log_pos 8024 CRC32 0xd2880cf0 	Anonymous_GTID	last_committed=34	sequence_number=35	rbr_only=no	original_committed_timestamp=1762792919523027	immediate_commit_timestamp=1762792919523027	transaction_length=304
# original_commit_timestamp=1762792919523027 (2025-11-11 01:41:59.523027 JST)
# immediate_commit_timestamp=1762792919523027 (2025-11-11 01:41:59.523027 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792919523027*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 8024
#251111  1:41:59 server id 1  end_log_pos 8249 CRC32 0x3eab0997 	Query	thread_id=12	exec_time=0	error_code=0	Xid = 230
SET TIMESTAMP=1762792919/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/* ApplicationName=RubyMine 2025.1 */ create table books
(
    id    int auto_increment
        primary key,
    price int null
)
/*!*/;
# at 8249
#251111  1:42:26 server id 1  end_log_pos 8328 CRC32 0xf5f7511d 	Anonymous_GTID	last_committed=35	sequence_number=36	rbr_only=yes	original_committed_timestamp=1762792946777212	immediate_commit_timestamp=1762792946777212	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762792946777212 (2025-11-11 01:42:26.777212 JST)
# immediate_commit_timestamp=1762792946777212 (2025-11-11 01:42:26.777212 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792946777212*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 8328
#251111  1:42:26 server id 1  end_log_pos 8407 CRC32 0xcc203d92 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762792946/*!*/;
BEGIN
/*!*/;
# at 8407
#251111  1:42:26 server id 1  end_log_pos 8463 CRC32 0xa3c0ce48 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 8463
#251111  1:42:26 server id 1  end_log_pos 8507 CRC32 0x8548b607 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=1
###   @2=10
# at 8507
#251111  1:42:26 server id 1  end_log_pos 8538 CRC32 0x2bf005a9 	Xid = 321
COMMIT/*!*/;
# at 8538
#251111  1:42:32 server id 1  end_log_pos 8617 CRC32 0xa93641c8 	Anonymous_GTID	last_committed=35	sequence_number=37	rbr_only=yes	original_committed_timestamp=1762792952814195	immediate_commit_timestamp=1762792952814195	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762792952814195 (2025-11-11 01:42:32.814195 JST)
# immediate_commit_timestamp=1762792952814195 (2025-11-11 01:42:32.814195 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792952814195*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 8617
#251111  1:42:32 server id 1  end_log_pos 8696 CRC32 0xb6892a70 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762792952/*!*/;
BEGIN
/*!*/;
# at 8696
#251111  1:42:32 server id 1  end_log_pos 8752 CRC32 0xbafa4870 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 8752
#251111  1:42:32 server id 1  end_log_pos 8796 CRC32 0x7a4264b9 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=2
###   @2=20
# at 8796
#251111  1:42:32 server id 1  end_log_pos 8827 CRC32 0x631f286d 	Xid = 343
COMMIT/*!*/;
# at 8827
#251111  1:42:36 server id 1  end_log_pos 8906 CRC32 0xb9faa5c8 	Anonymous_GTID	last_committed=35	sequence_number=38	rbr_only=yes	original_committed_timestamp=1762792956579650	immediate_commit_timestamp=1762792956579650	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762792956579650 (2025-11-11 01:42:36.579650 JST)
# immediate_commit_timestamp=1762792956579650 (2025-11-11 01:42:36.579650 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792956579650*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 8906
#251111  1:42:36 server id 1  end_log_pos 8985 CRC32 0x446bbd17 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762792956/*!*/;
BEGIN
/*!*/;
# at 8985
#251111  1:42:36 server id 1  end_log_pos 9041 CRC32 0xac0eaa3a 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 9041
#251111  1:42:36 server id 1  end_log_pos 9085 CRC32 0x3cac2ce0 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=3
###   @2=30
# at 9085
#251111  1:42:36 server id 1  end_log_pos 9116 CRC32 0xa1a61f13 	Xid = 365
COMMIT/*!*/;
# at 9116
#251111  1:42:39 server id 1  end_log_pos 9195 CRC32 0xe5e6fa30 	Anonymous_GTID	last_committed=35	sequence_number=39	rbr_only=yes	original_committed_timestamp=1762792959800421	immediate_commit_timestamp=1762792959800421	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762792959800421 (2025-11-11 01:42:39.800421 JST)
# immediate_commit_timestamp=1762792959800421 (2025-11-11 01:42:39.800421 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792959800421*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 9195
#251111  1:42:39 server id 1  end_log_pos 9274 CRC32 0x9f047b03 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762792959/*!*/;
BEGIN
/*!*/;
# at 9274
#251111  1:42:39 server id 1  end_log_pos 9330 CRC32 0xb4f511d6 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 9330
#251111  1:42:39 server id 1  end_log_pos 9374 CRC32 0x22bec93d 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=4
###   @2=40
# at 9374
#251111  1:42:39 server id 1  end_log_pos 9405 CRC32 0xa9709a75 	Xid = 387
COMMIT/*!*/;
# at 9405
#251111  1:42:43 server id 1  end_log_pos 9484 CRC32 0x3d4dd6fa 	Anonymous_GTID	last_committed=35	sequence_number=40	rbr_only=yes	original_committed_timestamp=1762792963153739	immediate_commit_timestamp=1762792963153739	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762792963153739 (2025-11-11 01:42:43.153739 JST)
# immediate_commit_timestamp=1762792963153739 (2025-11-11 01:42:43.153739 JST)
/*!80001 SET @@session.original_commit_timestamp=1762792963153739*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 9484
#251111  1:42:43 server id 1  end_log_pos 9563 CRC32 0xed9a875b 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762792963/*!*/;
BEGIN
/*!*/;
# at 9563
#251111  1:42:43 server id 1  end_log_pos 9619 CRC32 0xc6b19771 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 9619
#251111  1:42:43 server id 1  end_log_pos 9663 CRC32 0xf47b4c32 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=5
###   @2=50
# at 9663
#251111  1:42:43 server id 1  end_log_pos 9694 CRC32 0xe6bd9257 	Xid = 409
COMMIT/*!*/;
# at 9694
#251111  1:46:29 server id 1  end_log_pos 9773 CRC32 0x2f1cca72 	Anonymous_GTID	last_committed=35	sequence_number=41	rbr_only=yes	original_committed_timestamp=1762793189954863	immediate_commit_timestamp=1762793189954863	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793189954863 (2025-11-11 01:46:29.954863 JST)
# immediate_commit_timestamp=1762793189954863 (2025-11-11 01:46:29.954863 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793189954863*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 9773
#251111  1:46:29 server id 1  end_log_pos 9852 CRC32 0x7979f982 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793189/*!*/;
BEGIN
/*!*/;
# at 9852
#251111  1:46:29 server id 1  end_log_pos 9908 CRC32 0x0498c8dc 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 9908
#251111  1:46:29 server id 1  end_log_pos 9952 CRC32 0x4cb82475 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=6
###   @2=60
# at 9952
#251111  1:46:29 server id 1  end_log_pos 9983 CRC32 0xc48afc6b 	Xid = 446
COMMIT/*!*/;
# at 9983
#251111  1:46:33 server id 1  end_log_pos 10062 CRC32 0x001bee3b 	Anonymous_GTID	last_committed=35	sequence_number=42	rbr_only=yes	original_committed_timestamp=1762793193798634	immediate_commit_timestamp=1762793193798634	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793193798634 (2025-11-11 01:46:33.798634 JST)
# immediate_commit_timestamp=1762793193798634 (2025-11-11 01:46:33.798634 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793193798634*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 10062
#251111  1:46:33 server id 1  end_log_pos 10141 CRC32 0x82fe9c48 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793193/*!*/;
BEGIN
/*!*/;
# at 10141
#251111  1:46:33 server id 1  end_log_pos 10197 CRC32 0xeae9c67c 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 10197
#251111  1:46:33 server id 1  end_log_pos 10241 CRC32 0xaa65e0ab 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=7
###   @2=70
# at 10241
#251111  1:46:33 server id 1  end_log_pos 10272 CRC32 0x2e6861ee 	Xid = 468
COMMIT/*!*/;
# at 10272
#251111  1:46:37 server id 1  end_log_pos 10351 CRC32 0x71b62ad1 	Anonymous_GTID	last_committed=35	sequence_number=43	rbr_only=yes	original_committed_timestamp=1762793197212609	immediate_commit_timestamp=1762793197212609	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793197212609 (2025-11-11 01:46:37.212609 JST)
# immediate_commit_timestamp=1762793197212609 (2025-11-11 01:46:37.212609 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793197212609*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 10351
#251111  1:46:37 server id 1  end_log_pos 10430 CRC32 0x99126336 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793197/*!*/;
BEGIN
/*!*/;
# at 10430
#251111  1:46:37 server id 1  end_log_pos 10486 CRC32 0x83647564 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 10486
#251111  1:46:37 server id 1  end_log_pos 10530 CRC32 0x3ed66465 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=8
###   @2=80
# at 10530
#251111  1:46:37 server id 1  end_log_pos 10561 CRC32 0x132afc3e 	Xid = 490
COMMIT/*!*/;
# at 10561
#251111  1:46:40 server id 1  end_log_pos 10640 CRC32 0x92d81f56 	Anonymous_GTID	last_committed=35	sequence_number=44	rbr_only=yes	original_committed_timestamp=1762793200767366	immediate_commit_timestamp=1762793200767366	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793200767366 (2025-11-11 01:46:40.767366 JST)
# immediate_commit_timestamp=1762793200767366 (2025-11-11 01:46:40.767366 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793200767366*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 10640
#251111  1:46:40 server id 1  end_log_pos 10719 CRC32 0x8880a947 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793200/*!*/;
BEGIN
/*!*/;
# at 10719
#251111  1:46:40 server id 1  end_log_pos 10775 CRC32 0x258f26ca 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 10775
#251111  1:46:40 server id 1  end_log_pos 10819 CRC32 0xee01dc00 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=9
###   @2=90
# at 10819
#251111  1:46:40 server id 1  end_log_pos 10850 CRC32 0xaf26e31c 	Xid = 512
COMMIT/*!*/;
# at 10850
#251111  1:46:44 server id 1  end_log_pos 10929 CRC32 0x3f35669f 	Anonymous_GTID	last_committed=35	sequence_number=45	rbr_only=yes	original_committed_timestamp=1762793204090856	immediate_commit_timestamp=1762793204090856	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793204090856 (2025-11-11 01:46:44.090856 JST)
# immediate_commit_timestamp=1762793204090856 (2025-11-11 01:46:44.090856 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793204090856*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 10929
#251111  1:46:44 server id 1  end_log_pos 11008 CRC32 0xdd820ed5 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793204/*!*/;
BEGIN
/*!*/;
# at 11008
#251111  1:46:44 server id 1  end_log_pos 11064 CRC32 0x983d10e4 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 11064
#251111  1:46:44 server id 1  end_log_pos 11108 CRC32 0x29daa115 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=10
###   @2=100
# at 11108
#251111  1:46:44 server id 1  end_log_pos 11139 CRC32 0x3b84e8cd 	Xid = 534
COMMIT/*!*/;
# at 11139
#251111  1:46:59 server id 1  end_log_pos 11218 CRC32 0x5c0e2a48 	Anonymous_GTID	last_committed=35	sequence_number=46	rbr_only=yes	original_committed_timestamp=1762793219225748	immediate_commit_timestamp=1762793219225748	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793219225748 (2025-11-11 01:46:59.225748 JST)
# immediate_commit_timestamp=1762793219225748 (2025-11-11 01:46:59.225748 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793219225748*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 11218
#251111  1:46:59 server id 1  end_log_pos 11297 CRC32 0xb99b644c 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793219/*!*/;
BEGIN
/*!*/;
# at 11297
#251111  1:46:59 server id 1  end_log_pos 11353 CRC32 0x3ab1e1e6 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 11353
#251111  1:46:59 server id 1  end_log_pos 11397 CRC32 0x6190736f 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=11
###   @2=110
# at 11397
#251111  1:46:59 server id 1  end_log_pos 11428 CRC32 0x119395a8 	Xid = 556
COMMIT/*!*/;
# at 11428
#251111  1:47:02 server id 1  end_log_pos 11507 CRC32 0xc1369a55 	Anonymous_GTID	last_committed=35	sequence_number=47	rbr_only=yes	original_committed_timestamp=1762793222212982	immediate_commit_timestamp=1762793222212982	transaction_length=289
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793222212982 (2025-11-11 01:47:02.212982 JST)
# immediate_commit_timestamp=1762793222212982 (2025-11-11 01:47:02.212982 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793222212982*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 11507
#251111  1:47:02 server id 1  end_log_pos 11586 CRC32 0x556800e9 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793222/*!*/;
BEGIN
/*!*/;
# at 11586
#251111  1:47:02 server id 1  end_log_pos 11642 CRC32 0x164154ab 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 11642
#251111  1:47:02 server id 1  end_log_pos 11686 CRC32 0x89827e53 	Write_rows: table id 104 flags: STMT_END_F
### INSERT INTO `pensieve`.`books`
### SET
###   @1=12
###   @2=120
# at 11686
#251111  1:47:02 server id 1  end_log_pos 11717 CRC32 0x177be0ff 	Xid = 578
COMMIT/*!*/;
# at 11717
#251111  1:47:26 server id 1  end_log_pos 11796 CRC32 0xfe2e4241 	Anonymous_GTID	last_committed=47	sequence_number=48	rbr_only=yes	original_committed_timestamp=1762793246597512	immediate_commit_timestamp=1762793246597512	transaction_length=304
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793246597512 (2025-11-11 01:47:26.597512 JST)
# immediate_commit_timestamp=1762793246597512 (2025-11-11 01:47:26.597512 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793246597512*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 11796
#251111  1:47:26 server id 1  end_log_pos 11884 CRC32 0xe88363b4 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793246/*!*/;
BEGIN
/*!*/;
# at 11884
#251111  1:47:26 server id 1  end_log_pos 11940 CRC32 0x57626230 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 11940
#251111  1:47:26 server id 1  end_log_pos 11990 CRC32 0x3d0e216f 	Update_rows: table id 104 flags: STMT_END_F
### UPDATE `pensieve`.`books`
### WHERE
###   @1=12
###   @2=120
### SET
###   @1=12
###   @2=NULL
# at 11990
#251111  1:47:26 server id 1  end_log_pos 12021 CRC32 0xba5dee3b 	Xid = 649
COMMIT/*!*/;
# at 12021
#251111  1:47:28 server id 1  end_log_pos 12100 CRC32 0x55bc1bf3 	Anonymous_GTID	last_committed=46	sequence_number=49	rbr_only=yes	original_committed_timestamp=1762793248641170	immediate_commit_timestamp=1762793248641170	transaction_length=304
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793248641170 (2025-11-11 01:47:28.641170 JST)
# immediate_commit_timestamp=1762793248641170 (2025-11-11 01:47:28.641170 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793248641170*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 12100
#251111  1:47:28 server id 1  end_log_pos 12188 CRC32 0xf48a117f 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793248/*!*/;
BEGIN
/*!*/;
# at 12188
#251111  1:47:28 server id 1  end_log_pos 12244 CRC32 0x693a508a 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 12244
#251111  1:47:28 server id 1  end_log_pos 12294 CRC32 0x3e6703f6 	Update_rows: table id 104 flags: STMT_END_F
### UPDATE `pensieve`.`books`
### WHERE
###   @1=11
###   @2=110
### SET
###   @1=11
###   @2=NULL
# at 12294
#251111  1:47:28 server id 1  end_log_pos 12325 CRC32 0x76562e30 	Xid = 671
COMMIT/*!*/;
# at 12325
#251111  1:47:30 server id 1  end_log_pos 12404 CRC32 0xd161e192 	Anonymous_GTID	last_committed=45	sequence_number=50	rbr_only=yes	original_committed_timestamp=1762793250531507	immediate_commit_timestamp=1762793250531507	transaction_length=304
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793250531507 (2025-11-11 01:47:30.531507 JST)
# immediate_commit_timestamp=1762793250531507 (2025-11-11 01:47:30.531507 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793250531507*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 12404
#251111  1:47:30 server id 1  end_log_pos 12492 CRC32 0x66923ffd 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793250/*!*/;
BEGIN
/*!*/;
# at 12492
#251111  1:47:30 server id 1  end_log_pos 12548 CRC32 0x9808cc1a 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 12548
#251111  1:47:30 server id 1  end_log_pos 12598 CRC32 0x71060793 	Update_rows: table id 104 flags: STMT_END_F
### UPDATE `pensieve`.`books`
### WHERE
###   @1=10
###   @2=100
### SET
###   @1=10
###   @2=NULL
# at 12598
#251111  1:47:30 server id 1  end_log_pos 12629 CRC32 0xf4010cec 	Xid = 693
COMMIT/*!*/;
# at 12629
#251111  1:47:32 server id 1  end_log_pos 12708 CRC32 0x37ad25ac 	Anonymous_GTID	last_committed=44	sequence_number=51	rbr_only=yes	original_committed_timestamp=1762793252623204	immediate_commit_timestamp=1762793252623204	transaction_length=304
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793252623204 (2025-11-11 01:47:32.623204 JST)
# immediate_commit_timestamp=1762793252623204 (2025-11-11 01:47:32.623204 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793252623204*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 12708
#251111  1:47:32 server id 1  end_log_pos 12796 CRC32 0xb0e5b52a 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793252/*!*/;
BEGIN
/*!*/;
# at 12796
#251111  1:47:32 server id 1  end_log_pos 12852 CRC32 0x2ee03328 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 12852
#251111  1:47:32 server id 1  end_log_pos 12902 CRC32 0x2254899f 	Update_rows: table id 104 flags: STMT_END_F
### UPDATE `pensieve`.`books`
### WHERE
###   @1=9
###   @2=90
### SET
###   @1=9
###   @2=NULL
# at 12902
#251111  1:47:32 server id 1  end_log_pos 12933 CRC32 0xe8309a38 	Xid = 715
COMMIT/*!*/;
# at 12933
#251111  1:47:34 server id 1  end_log_pos 13012 CRC32 0xc4d09233 	Anonymous_GTID	last_committed=43	sequence_number=52	rbr_only=yes	original_committed_timestamp=1762793254829047	immediate_commit_timestamp=1762793254829047	transaction_length=304
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793254829047 (2025-11-11 01:47:34.829047 JST)
# immediate_commit_timestamp=1762793254829047 (2025-11-11 01:47:34.829047 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793254829047*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 13012
#251111  1:47:34 server id 1  end_log_pos 13100 CRC32 0x34ef87d7 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793254/*!*/;
BEGIN
/*!*/;
# at 13100
#251111  1:47:34 server id 1  end_log_pos 13156 CRC32 0x8d9d259e 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 13156
#251111  1:47:34 server id 1  end_log_pos 13206 CRC32 0xc4168d65 	Update_rows: table id 104 flags: STMT_END_F
### UPDATE `pensieve`.`books`
### WHERE
###   @1=8
###   @2=80
### SET
###   @1=8
###   @2=NULL
# at 13206
#251111  1:47:34 server id 1  end_log_pos 13237 CRC32 0x2bde4f15 	Xid = 737
COMMIT/*!*/;
# at 13237
#251111  1:47:37 server id 1  end_log_pos 13316 CRC32 0x8ef63606 	Anonymous_GTID	last_committed=42	sequence_number=53	rbr_only=yes	original_committed_timestamp=1762793257061025	immediate_commit_timestamp=1762793257061025	transaction_length=304
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793257061025 (2025-11-11 01:47:37.061025 JST)
# immediate_commit_timestamp=1762793257061025 (2025-11-11 01:47:37.061025 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793257061025*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 13316
#251111  1:47:37 server id 1  end_log_pos 13404 CRC32 0x840d7ae5 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793257/*!*/;
BEGIN
/*!*/;
# at 13404
#251111  1:47:37 server id 1  end_log_pos 13460 CRC32 0x7992f5a9 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 13460
#251111  1:47:37 server id 1  end_log_pos 13510 CRC32 0x38ec7432 	Update_rows: table id 104 flags: STMT_END_F
### UPDATE `pensieve`.`books`
### WHERE
###   @1=7
###   @2=70
### SET
###   @1=7
###   @2=NULL
# at 13510
#251111  1:47:37 server id 1  end_log_pos 13541 CRC32 0xdb252a70 	Xid = 759
COMMIT/*!*/;
# at 13541
#251111  1:47:39 server id 1  end_log_pos 13620 CRC32 0x1f144006 	Anonymous_GTID	last_committed=41	sequence_number=54	rbr_only=yes	original_committed_timestamp=1762793259299253	immediate_commit_timestamp=1762793259299253	transaction_length=304
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793259299253 (2025-11-11 01:47:39.299253 JST)
# immediate_commit_timestamp=1762793259299253 (2025-11-11 01:47:39.299253 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793259299253*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 13620
#251111  1:47:39 server id 1  end_log_pos 13708 CRC32 0xebad00a5 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793259/*!*/;
BEGIN
/*!*/;
# at 13708
#251111  1:47:39 server id 1  end_log_pos 13764 CRC32 0xdaefe31f 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 13764
#251111  1:47:39 server id 1  end_log_pos 13814 CRC32 0x872eb382 	Update_rows: table id 104 flags: STMT_END_F
### UPDATE `pensieve`.`books`
### WHERE
###   @1=6
###   @2=60
### SET
###   @1=6
###   @2=NULL
# at 13814
#251111  1:47:39 server id 1  end_log_pos 13845 CRC32 0xc7a1f628 	Xid = 781
COMMIT/*!*/;
# at 13845
#251111  1:47:45 server id 1  end_log_pos 13924 CRC32 0x97877ae9 	Anonymous_GTID	last_committed=36	sequence_number=55	rbr_only=yes	original_committed_timestamp=1762793265393015	immediate_commit_timestamp=1762793265393015	transaction_length=304
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1762793265393015 (2025-11-11 01:47:45.393015 JST)
# immediate_commit_timestamp=1762793265393015 (2025-11-11 01:47:45.393015 JST)
/*!80001 SET @@session.original_commit_timestamp=1762793265393015*//*!*/;
/*!80014 SET @@session.original_server_version=90300*//*!*/;
/*!80014 SET @@session.immediate_server_version=90300*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 13924
#251111  1:47:45 server id 1  end_log_pos 14012 CRC32 0x218a6c55 	Query	thread_id=16	exec_time=0	error_code=0
SET TIMESTAMP=1762793265/*!*/;
BEGIN
/*!*/;
# at 14012
#251111  1:47:45 server id 1  end_log_pos 14068 CRC32 0xc2bad927 	Table_map: `pensieve`.`books` mapped to number 104
# has_generated_invisible_primary_key=0
# at 14068
#251111  1:47:45 server id 1  end_log_pos 14118 CRC32 0x54ec7d0b 	Update_rows: table id 104 flags: STMT_END_F
### UPDATE `pensieve`.`books`
### WHERE
###   @1=1
###   @2=10
### SET
###   @1=1
###   @2=NULL
# at 14118
#251111  1:47:45 server id 1  end_log_pos 14149 CRC32 0x902edf09 	Xid = 803
COMMIT/*!*/;
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;
